display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: வடிகட்டி
          reset_button_label: மீளமை
          exposed_sorts_label: வரிசையாக
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- அனைத்தும் -'
      fields:
        timestamp:
          label: தேதி
        name:
          label: பயனர்
          separator: ', '
        link:
          label: செயல்பாடுகள்
  page:
    display_title: பக்கம்
