display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: மீளமை
          exposed_sorts_label: வரிசையாக
      pager:
        options:
          tags:
            first: '« முதல்'
            last: 'கடந்த »'
          expose:
            items_per_page_options_all_label: '- அனைத்தும் -'
      fields:
        name:
          label: பயனர்
          separator: ', '
        group_roles:
          label: பாத்திரங்கள்
          separator: ', '
        changed:
          separator: ', '
        created:
          separator: ', '
        dropbutton:
          label: செயல்பாடுகள்
  page_1:
    display_title: பக்கம்
