display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: வடிகட்டி
          reset_button_label: மீளமை
          exposed_sorts_label: வரிசையாக
      pager:
        options:
          tags:
            previous: '‹ முந்திய'
            next: 'அடுத்த ›'
            first: '« முதல்'
            last: 'கடந்த »'
      fields:
        type:
          label: 'உள்ளடக்க வகை'
          separator: ', '
        status:
          label: நிலை
        operations:
          label: செயல்பாடுகள்
      filters:
        type:
          expose:
            label: 'உள்ளடக்க வகை'
        status:
          expose:
            label: நிலை
        langcode:
          expose:
            label: மொழி
  page_1:
    display_title: பக்கம்
