display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: மீளமை
          exposed_sorts_label: வரிசையாக
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- அனைத்தும் -'
      filters:
        name:
          expose:
            label: பெயர்
        langcode:
          expose:
            label: மொழி
  page:
    display_title: பக்கம்
    display_options:
      fields:
        name:
          separator: ', '
        edit_media:
          text: மாற்று
        delete_media:
          text: அழி
  widget:
    display_options:
      filters:
        name:
          expose:
            label: பெயர்
  widget_table:
    display_options:
      fields:
        name:
          label: பெயர்
      filters:
        name:
          expose:
            label: பெயர்
