display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: மீளமை
          exposed_sorts_label: வரிசையாக
      pager:
        options:
          tags:
            first: '« முதல்'
            last: 'கடந்த »'
          expose:
            items_per_page_options_all_label: '- அனைத்தும் -'
      fields:
        sid:
          separator: ', '
        in_draft:
          separator: ', '
        created:
          label: உருவாக்கப்பட்டது
          separator: ', '
        remote_addr:
          separator: ', '
        view_webform_submission:
          label: செயல்பாடுகள்
  embed_administer:
    display_options:
      fields:
        sid:
          separator: ', '
        in_draft:
          separator: ', '
        sticky:
          separator: ', '
        locked:
          separator: ', '
        created:
          label: உருவாக்கப்பட்டது
          separator: ', '
        completed:
          separator: ', '
        remote_addr:
          separator: ', '
        operations:
          label: செயல்பாடுகள்
  embed_manage:
    display_options:
      fields:
        sid:
          separator: ', '
        in_draft:
          separator: ', '
        sticky:
          separator: ', '
        locked:
          separator: ', '
        created:
          label: உருவாக்கப்பட்டது
          separator: ', '
        completed:
          separator: ', '
        remote_addr:
          separator: ', '
        view_webform_submission:
          label: செயல்பாடுகள்
        edit_webform_submission:
          label: செயல்பாடுகள்
  embed_review:
    display_options:
      fields:
        sid:
          separator: ', '
        in_draft:
          separator: ', '
        sticky:
          separator: ', '
        locked:
          separator: ', '
        created:
          label: உருவாக்கப்பட்டது
          separator: ', '
        completed:
          separator: ', '
        remote_addr:
          separator: ', '
        view_webform_submission:
          label: செயல்பாடுகள்
