display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: வடிகட்டி
          reset_button_label: மீளமை
          exposed_sorts_label: வரிசையாக
      pager:
        options:
          tags:
            previous: '‹ முந்திய'
            next: 'அடுத்த ›'
          expose:
            items_per_page_options_all_label: '- அனைத்தும் -'
      fields:
        filename:
          label: பெயர்
          separator: ', '
        status:
          label: நிலை
      filters:
        filename:
          expose:
            label: 'கோப்பு பெயர்'
        status:
          expose:
            label: நிலை
  page_2:
    display_options:
      pager:
        options:
          tags:
            previous: '‹ முந்திய'
            next: 'அடுத்த ›'
          expose:
            items_per_page_options_all_label: '- அனைத்தும் -'
      fields:
        entity_label:
          label: உருப்படி
