display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: மீளமை
          exposed_sorts_label: வரிசையாக
      filters:
        access:
          expose:
            label: 'கடைசி அனுகல்'
