display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: வடிகட்டி
          reset_button_label: மீளமை
          exposed_sorts_label: வரிசையாக
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- அனைத்தும் -'
          tags:
            previous: '‹ முந்திய'
            next: 'அடுத்த ›'
            first: '« முதல்'
            last: 'கடந்த »'
      fields:
        thumbnail__target_id:
          separator: ', '
        name:
          separator: ', '
        bundle:
          separator: ', '
        uid:
          separator: ', '
        status:
          label: நிலை
          separator: ', '
        changed:
          separator: ', '
        operations:
          label: செயல்பாடுகள்
      filters:
        langcode:
          expose:
            label: மொழி
