display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: மீளமை
          exposed_sorts_label: வரிசையாக
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- அனைத்தும் -'
  page_1:
    display_title: பக்கம்
