label: মাধ্যম
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: ফিল্টার
      fields:
        bundle:
          label: টাইপ
        uid:
          label: লেখক
        status:
          label: স্ট্যাটাস
          settings:
            format_custom_true: প্রকাশিত
        changed:
          label: আপডেটকৃত
        operations:
          label: কার্যাবলী
      filters:
        bundle:
          expose:
            label: টাইপ
        status:
          group_info:
            group_items:
              1:
                title: প্রকাশিত
        langcode:
          expose:
            label: ভাষা
      title: মাধ্যম
  media_page_list:
    display_title: মাধ্যম
    display_options:
      menu:
        title: মাধ্যম
