display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: ফিল্টার
      fields:
        type:
          label: টাইপ
        timestamp:
          label: তারিখ
        message:
          label: বার্তা
        name:
          label: ব্যবহারকারী
        link:
          label: কার্যাবলী
      filters:
        type:
          expose:
            label: টাইপ
      empty:
        area:
          admin_label: 'কোন লগ বার্তা নেই।'
          content: 'কোন লগ বার্তা নেই।'
