label: কনটেন্ট
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: ফিল্টার
      fields:
        title:
          label: শিরোনাম
        type:
          label: 'কন্টেন্টের ধরণ'
        name:
          label: লেখক
        status:
          label: স্ট্যাটাস
          settings:
            format_custom_true: প্রকাশিত
        changed:
          label: আপডেটকৃত
        operations:
          label: কার্যাবলী
      filters:
        title:
          expose:
            label: শিরোনাম
        type:
          expose:
            label: 'কন্টেন্টের ধরণ'
        status:
          expose:
            label: স্ট্যাটাস
          group_info:
            group_items:
              1:
                title: প্রকাশিত
        langcode:
          expose:
            label: ভাষা
      title: কনটেন্ট
      empty:
        area_text_custom:
          content: 'কোন কন্টেন্ট নেই।'
  page_1:
    display_options:
      menu:
        title: কনটেন্ট
      tab_options:
        title: কনটেন্ট
