display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: వడపోయి
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- అన్ని -'
      fields:
        operations:
          label: కార్యాలు
      use_more_text: మరిన్ని
  page_unapproved:
    display_options:
      fields:
        operations:
          label: కార్యాలు
