display:
  default:
    display_options:
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- అన్ని -'
  page:
    display_title: పేజీ
    display_options:
      fields:
        edit_media:
          text: మార్చు
        delete_media:
          text: తొలగించు
