display:
  default:
    display_options:
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- అన్ని -'
          tags:
            previous: '‹ మునుపటి'
            next: 'తదుపరి ›'
            first: '« మొదటి'
            last: 'చివర »'
  page_1:
    display_title: పేజీ
