display:
  default:
    display_options:
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- అన్ని -'
      filters:
        name:
          expose:
            label: పేరు
        langcode:
          expose:
            label: భాష
  page:
    display_title: పేజీ
    display_options:
      fields:
        edit_media:
          text: మార్చు
        delete_media:
          text: తొలగించు
  widget:
    display_options:
      filters:
        name:
          expose:
            label: పేరు
  widget_table:
    display_options:
      fields:
        name:
          label: పేరు
      filters:
        name:
          expose:
            label: పేరు
