settings:
  default_submit_button_label: 'जमा करें'
  default_reset_button_label: 'दोबारा से स्थापित करें|'
  default_delete_button_label: मिटायें
  default_preview_next_button_label: 'पूर्वावलोकन (प्रिविउ)'
  default_preview_label: 'पूर्वावलोकन (प्रिविउ)'
  default_preview_title: '[webform:title]: पूर्वावलोकन (प्रिविउ)'
  default_preview_message: 'कृपया अपने दिये गये उत्तर दुबरा देख ले । जब तक आप "सबमिट" बटन नहीं दबाते, तब तक आपके उत्तर सेव नहीं किये जाएंगे!'
  dialog_options:
    narrow:
      title: संकीर्ण
    normal:
      title: सामान्य
    wide:
      title: चौड़ा
element:
  default_more_title: अधिक
