module:
  webform_clientside_validation: -1
  action: 0
  administerusersbyrole: 0
  advagg: 0
  advagg_cdn: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  charts: 0
  charts_google: 0
  charts_highcharts: 0
  ckeditor: 0
  clientside_validation: 0
  clientside_validation_jquery: 0
  color: 0
  comment: 0
  config: 0
  config_translation: 0
  contact: 0
  contextual: 0
  ctools: 0
  date_popup: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  eva: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gnode: 0
  group: 0
  help: 0
  history: 0
  image: 0
  imce: 0
  inline_form_errors: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  potx: 0
  pwa: 0
  pwa_extras: 0
  quickedit: 0
  rdf: 0
  responsive_image: 0
  rest: 0
  rest_views: 0
  role_delegation: 0
  search: 0
  serialization: 0
  shortcut: 0
  smart_date: 0
  subgroup: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  variationcache: 0
  views_aggregator: 0
  views_aggregator_more_functions: 0
  views_fields_on_off: 0
  views_flipped_table: 0
  views_simple_math_field: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_attachment: 0
  webform_cards: 0
  webform_composite: 0
  webform_group: 0
  webform_image_select: 0
  webform_node: 0
  webform_options_custom: 0
  webform_options_limit: 0
  webform_submission_export_import: 0
  webform_submission_log: 0
  webform_templates: 0
  webform_ui: 0
  webform_views: 0
  pathauto: 1
  webform_bootstrap: 1
  content_translation: 10
  views: 10
  lingotek: 15
  standard: 1000
theme:
  bartik: 0
  seven: 0
  stable: 0
  classy: 0
  drupal8_w3css_theme: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
