site_name: INDIPROM
short_name: INDIPROM
description: 'PWA of INDIPROM website'
start_url: /
lang: en
theme_color: '#000000'
background_color: '#000000'
display: fullscreen
default_image: '0'
urls_to_cache: ''
urls_to_exclude: "admin/.*\r\nuser/.*"
offline_page: /offline
cache_version: '2'
cross_origin: true
skip_waiting: false
_core:
  default_config_hash: cP1TZQyv1WdET3iepl2QoyOPK7VeO0xHm0lU_FU1Wmc
image: '/sites/default/files/pwa/Logo for PWA.png'
image_small: '/sites/default/files/pwa/Logo for PWA.pngcopy.png'
image_very_small: '/sites/default/files/pwa/Logo for PWA.pngcopy2.png'
